# These are supported funding model platforms

github: dscanavall11
patreon: https://patreon.com/Dscanavall
# open_collective: # Reemplaza con tu usuario de Open Collective
# ko_fi: # Reemplaza con tu usuario de Ko-fi
tidelift: npm/@haic/cli # Habilitado para tu paquete de npm
# community_bridge: 
# liberapay: 
# issuehunt: 
# lfx_crowdfunding: 
# polar: 
buy_me_a_coffee: https://buymeacoffee.com/dscanavall
# thanks_dev: 
custom: ['https://www.npmjs.com/package/@haic/cli'] # Enlace directo a la documentación de tu lenguaje
