/**
 * YAGNI, enforced.
 *
 * This is the pass the whole language exists for. A model generated by an AI
 * tends to grow scaffolding nobody asked for: dtos that mirror aggregates,
 * ports with one caller, services that forward a single call. Each of those is
 * cheap to write and expensive to keep, so the compiler names them out loud.
 *
 * Everything here is a warning, never an error: unused code is a smell, not a
 * contradiction. `ail check --strict` turns them into failures.
 */
import {
  normalisePhrase,
  referencedNames,
  typeEquals,
  type IRDeclaration,
  type IRField,
  type SourceSpan,
} from '@ai-lang/core';
import type { AnalysisContext, SemanticPass } from '../context.js';
import { typesOfDeclaration, walkExpressions, walkStatements } from '../walk.js';

export const simplicityPass: SemanticPass = {
  id: 'simplicity',
  stage: 'ddd',
  run(context) {
    const referenced = collectReferences(context);
    reportUnreachableDeclarations(context, referenced);
    reportDuplicateShapes(context);
    reportPassThroughOperations(context);
    reportUnusedPorts(context);
    reportSpeculativeFields(context, referenced);
  },
};

/** Names mentioned anywhere other than their own declaration. */
function collectReferences(context: AnalysisContext): Map<string, Set<string>> {
  const uses = new Map<string, Set<string>>();
  const record = (name: string, by: string): void => {
    const bucket = uses.get(name) ?? new Set<string>();
    bucket.add(by);
    uses.set(name, bucket);
  };

  for (const declaration of context.module.declarations) {
    for (const use of typesOfDeclaration(declaration)) {
      for (const name of referencedNames(use.type)) if (name !== declaration.name) record(name, declaration.name);
    }
    if (declaration.kind === 'aggregate') {
      for (const name of [...declaration.entities, ...declaration.emits]) record(name, declaration.name);
    }
    if (declaration.kind === 'service') {
      for (const name of declaration.uses) record(name, declaration.name);
      if (declaration.implements) record(declaration.implements, declaration.name);
    }
    if (declaration.kind === 'adapter') record(declaration.implements, declaration.name);
    if (declaration.kind === 'handler') {
      record(declaration.on, declaration.name);
      for (const name of declaration.uses) record(name, declaration.name);
    }
    if (declaration.kind === 'endpoint') {
      record(declaration.handler.service, declaration.name);
      for (const response of declaration.responses) if (response.when) record(response.when, declaration.name);
    }
    if (declaration.kind === 'command' && declaration.target) record(declaration.target, declaration.name);
    if (declaration.kind === 'event' && declaration.source) record(declaration.source, declaration.name);

    for (const body of bodiesOf(declaration)) {
      for (const expression of walkExpressions(body)) {
        if (expression.kind === 'construct') record(expression.type, declaration.name);
      }
      for (const statement of walkStatements(body)) {
        if (statement.kind === 'publish') record(statement.event, declaration.name);
        if (statement.kind === 'fail') record(statement.error, declaration.name);
      }
    }
  }
  return uses;
}

/** Reachability from the module's entry points: endpoints, handlers, adapters. */
function reportUnreachableDeclarations(context: AnalysisContext, referenced: Map<string, Set<string>>): void {
  const rooted = new Set<string>();
  const queue: string[] = [];

  for (const declaration of context.module.declarations) {
    if (declaration.kind === 'endpoint' || declaration.kind === 'handler' || declaration.kind === 'adapter') {
      rooted.add(declaration.name);
      queue.push(declaration.name);
    }
  }
  // Everything an entry point transitively mentions is reachable.
  const dependencies = invert(referenced);
  while (queue.length > 0) {
    const current = queue.pop()!;
    for (const next of dependencies.get(current) ?? []) {
      if (rooted.has(next)) continue;
      rooted.add(next);
      queue.push(next);
    }
  }
  if (rooted.size === 0) return; // A library module has no entry points; skip.

  for (const declaration of context.module.declarations) {
    if (rooted.has(declaration.name)) continue;
    if (declaration.kind === 'error') continue; // The error-flow pass owns those.
    // A scenario is the thing that reaches in, so nothing reaches it.
    if (declaration.kind === 'scenario') continue;
    context.diagnostics.warn(
      'ddd',
      'AIL2501',
      `${declaration.kind} ${declaration.name} is never reached from an endpoint, handler or adapter`,
      declaration.span ?? fallback(context),
      { hint: 'delete it, or wire it into the flow it was written for' },
    );
  }
}

/** Two declarations with the same field shape mean one of them is redundant. */
function reportDuplicateShapes(context: AnalysisContext): void {
  const byShape = new Map<string, IRDeclaration[]>();
  for (const declaration of context.index.dataShapes) {
    if (declaration.kind === 'error') continue;
    if (declaration.fields.length === 0) continue;
    const key = shapeKey(declaration.fields);
    byShape.set(key, [...(byShape.get(key) ?? []), declaration]);
  }

  for (const group of byShape.values()) {
    if (group.length < 2) continue;
    const [first, ...rest] = group;
    for (const duplicate of rest) {
      context.diagnostics.warn(
        'ddd',
        'AIL2502',
        `${duplicate.kind} ${duplicate.name} has exactly the same fields as ${first!.kind} ${first!.name}`,
        duplicate.span ?? fallback(context),
        {
          hint:
            duplicate.kind === 'dto'
              ? `a dto exists to carry less than the model; either drop fields or reuse ${first!.name}`
              : `keep one of the two and reference it from the other`,
          related: first!.span ? [{ message: `first shape declared here`, span: first!.span }] : [],
        },
      );
    }
  }
}

/**
 * A service operation that forwards one call unchanged adds a hop, not a
 * behaviour — unless it implements an inbound port, where forwarding *is* the
 * boundary. A CRUD read is the honest case: there is no rule to hold, and the
 * use case still has to exist for the outside world to reach the port.
 */
function reportPassThroughOperations(context: AnalysisContext): void {
  for (const service of context.index.services) {
    const boundary = service.implements ? context.index.typed(service.implements, 'port') : undefined;

    for (const operation of service.operations) {
      const isUseCase = boundary?.operations.some((o) => normalisePhrase(o.phrase) === normalisePhrase(operation.phrase));
      if (isUseCase) continue;
      const meaningful = operation.body.filter((s) => s.kind !== 'return' || s.value !== null);
      if (meaningful.length !== 1) continue;

      const only = meaningful[0]!;
      const call = only.kind === 'perform' ? only.value : only.kind === 'return' ? only.value : null;
      if (call?.kind !== 'call') continue;

      const forwardsEverything =
        call.arguments.length === operation.parameters.length &&
        call.arguments.every((argument) => argument.value.kind === 'reference' && argument.value.path.length === 1);
      if (!forwardsEverything) continue;

      context.diagnostics.warn(
        'ddd',
        'AIL2503',
        `${service.name}.${operation.phrase} only forwards "${call.operation}"`,
        operation.span ?? service.span ?? fallback(context),
        { hint: 'let the caller use the port directly, or add the rule this operation was meant to hold' },
      );
    }
  }
}

/** A port with no caller is an abstraction bought before it was needed. */
function reportUnusedPorts(context: AnalysisContext): void {
  const callers = new Map<string, Set<string>>();
  for (const declaration of context.module.declarations) {
    if (declaration.kind === 'service' || declaration.kind === 'handler') {
      for (const name of declaration.uses) {
        callers.set(name, (callers.get(name) ?? new Set()).add(declaration.name));
      }
    }
  }
  for (const port of context.index.ports) {
    if (port.direction === 'inbound') continue;
    if ((callers.get(port.name)?.size ?? 0) > 0) continue;
    context.diagnostics.warn(
      'ddd',
      'AIL2504',
      `port ${port.name} has no callers`,
      port.span ?? fallback(context),
      { hint: 'add it to the "uses" line of the service that needs it, or delete it' },
    );
  }
}

/**
 * Declarations that cross the module boundary. Every field of an exposed shape
 * is justified by the contract that carries it, so those are never flagged.
 */
function exposedShapes(context: AnalysisContext): Set<string> {
  const exposed = new Set<string>();
  const queue: string[] = [];

  const seed = (type: { kind: string } | undefined): void => {
    if (!type) return;
    for (const name of referencedNames(type as Parameters<typeof referencedNames>[0])) queue.push(name);
  };

  for (const endpoint of context.index.endpoints) {
    seed(endpoint.request);
    for (const response of endpoint.responses) seed(response.body);
  }
  for (const event of context.index.events) queue.push(event.name);

  while (queue.length > 0) {
    const name = queue.pop()!;
    if (exposed.has(name)) continue;
    exposed.add(name);
    const declaration = context.index.get(name);
    if (!declaration || !('fields' in declaration)) continue;
    for (const field of declaration.fields) {
      for (const referencedName of referencedNames(field.type)) queue.push(referencedName);
    }
  }
  return exposed;
}

/** Fields that no rule, projection or contract ever mentions. */
function reportSpeculativeFields(context: AnalysisContext, referenced: Map<string, Set<string>>): void {
  const exposed = exposedShapes(context);
  const mentionedPaths = new Set<string>();
  for (const declaration of context.module.declarations) {
    for (const body of bodiesOf(declaration)) {
      for (const expression of walkExpressions(body)) {
        if (expression.kind === 'reference') for (const part of expression.path) mentionedPaths.add(part);
        if (expression.kind === 'construct') for (const argument of expression.arguments) mentionedPaths.add(argument.name);
        if (expression.kind === 'call') for (const argument of expression.arguments) mentionedPaths.add(argument.name);
      }
      for (const statement of walkStatements(body)) {
        if (statement.kind === 'set' || statement.kind === 'append' || statement.kind === 'remove') {
          for (const part of statement.kind === 'set' ? statement.target : statement.collection) mentionedPaths.add(part);
        }
        if (statement.kind === 'publish' || statement.kind === 'fail') {
          for (const argument of statement.arguments) mentionedPaths.add(argument.name);
        }
      }
    }
    if ('invariants' in declaration) {
      for (const invariant of declaration.invariants) {
        for (const expression of walkExpressions([{ kind: 'perform', value: invariant.condition }])) {
          if (expression.kind === 'reference') for (const part of expression.path) mentionedPaths.add(part);
        }
      }
    }
  }

  for (const aggregate of [...context.index.aggregates, ...context.index.entities]) {
    // A shape carried over the wire justifies every field it declares.
    if (exposed.has(aggregate.name)) continue;
    if ((referenced.get(aggregate.name)?.size ?? 0) === 0) continue;
    for (const field of aggregate.fields) {
      if (field.identity || aggregate.identity.includes(field.name)) continue;
      if (mentionedPaths.has(field.name)) continue;
      context.diagnostics.info(
        'ddd',
        'AIL2505',
        `${aggregate.name}.${field.name} is stored but never read or written`,
        field.span ?? aggregate.span ?? fallback(context),
        { hint: 'keep it only if something outside this module needs it' },
      );
    }
  }
}

function shapeKey(fields: readonly IRField[]): string {
  return [...fields]
    .map((f) => `${f.name}:${JSON.stringify(f.type)}:${f.required}`)
    .sort()
    .join('|');
}

function invert(map: Map<string, Set<string>>): Map<string, Set<string>> {
  const out = new Map<string, Set<string>>();
  for (const [target, sources] of map) {
    for (const source of sources) {
      out.set(source, (out.get(source) ?? new Set()).add(target));
    }
  }
  return out;
}

function bodiesOf(declaration: IRDeclaration): Array<Parameters<typeof walkStatements>[0]> {
  if (declaration.kind === 'service' || declaration.kind === 'aggregate' || declaration.kind === 'adapter') {
    return declaration.operations.map((o) => o.body);
  }
  if (declaration.kind === 'handler') return [declaration.body];
  return [];
}

function fallback(context: AnalysisContext): SourceSpan {
  const file = context.module.source?.file ?? '<unknown>';
  return { file, start: { line: 1, column: 1, offset: 0 }, end: { line: 1, column: 1, offset: 0 } };
}

export { typeEquals };
