/**
 * Text emission primitives shared by every generator.
 *
 * Generators never concatenate strings by hand: they push lines into a
 * `CodeWriter`, which owns indentation and trailing-newline policy. That keeps
 * emitted files byte-stable, which the cross-target verifier depends on.
 */

export interface GeneratedFile {
  /** Path relative to the output root, always with forward slashes. */
  path: string;
  contents: string;
  /** `true` when the file must be marked executable on POSIX systems. */
  executable?: boolean;
}

export class CodeWriter {
  private readonly lines: string[] = [];
  private depth = 0;

  constructor(private readonly indentUnit = '  ') {}

  indent(): this {
    this.depth += 1;
    return this;
  }

  dedent(): this {
    this.depth = Math.max(0, this.depth - 1);
    return this;
  }

  /** Writes `body()` one level deeper, then restores the previous level. */
  block(body: () => void): this {
    this.indent();
    body();
    this.dedent();
    return this;
  }

  line(text = ''): this {
    if (text === '') this.lines.push('');
    else for (const part of text.split('\n')) this.lines.push(`${this.indentUnit.repeat(this.depth)}${part}`);
    return this;
  }

  lines_(texts: readonly string[]): this {
    for (const t of texts) this.line(t);
    return this;
  }

  /** Adds a blank line unless the buffer is empty or already ends with one. */
  blank(): this {
    if (this.lines.length > 0 && this.lines[this.lines.length - 1] !== '') this.lines.push('');
    return this;
  }

  /** Emits `items` separated by `separator`, with the separator omitted on the last. */
  joinLines(items: readonly string[], separator: string): this {
    items.forEach((item, i) => this.line(i === items.length - 1 ? item : `${item}${separator}`));
    return this;
  }

  toString(): string {
    const body = this.lines.join('\n').replace(/\s+$/, '');
    return body.length > 0 ? `${body}\n` : '';
  }
}

/** Wraps `text` to `width` columns and prefixes every line with `prefix`. */
export function comment(text: string, prefix = '// ', width = 100): string[] {
  const limit = Math.max(20, width - prefix.length);
  const out: string[] = [];
  for (const paragraph of text.split('\n')) {
    let current = '';
    for (const word of paragraph.split(/\s+/).filter(Boolean)) {
      if (current.length === 0) current = word;
      else if (current.length + 1 + word.length <= limit) current += ` ${word}`;
      else {
        out.push(prefix + current);
        current = word;
      }
    }
    out.push(prefix + current);
  }
  return out;
}

export const GENERATED_BANNER = 'Generated by AI-Lang. Edit the .ail source and recompile; changes here are overwritten.';

export function file(path: string, contents: string, executable = false): GeneratedFile {
  return executable ? { path, contents, executable } : { path, contents };
}

/** Serialises a plain object as YAML. Supports the subset the IaC layer needs. */
export function toYaml(value: unknown, depth = 0): string {
  const pad = '  '.repeat(depth);
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'string') return needsYamlQuotes(value) ? JSON.stringify(value) : value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return value
      .map((item) => {
        const rendered = toYaml(item, depth + 1);
        return isScalar(item) ? `${pad}- ${rendered}` : `${pad}-\n${indentBlock(rendered, depth + 1)}`;
      })
      .join('\n');
  }
  const entries = Object.entries(value as Record<string, unknown>).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '{}';
  return entries
    .map(([key, v]) => {
      if (isScalar(v)) return `${pad}${key}: ${toYaml(v, depth)}`;
      if (Array.isArray(v) && v.length === 0) return `${pad}${key}: []`;
      return `${pad}${key}:\n${toYaml(v, depth + 1)}`;
    })
    .join('\n');
}

function isScalar(value: unknown): boolean {
  return value === null || typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean';
}

function indentBlock(text: string, depth: number): string {
  const pad = '  '.repeat(depth);
  return text
    .split('\n')
    .map((l) => (l.startsWith(pad) ? l : pad + l.trimStart()))
    .join('\n');
}

function needsYamlQuotes(value: string): boolean {
  if (value === '') return true;
  if (/^[-?:,[\]{}#&*!|>'"%@`]/.test(value)) return true;
  if (/:\s/.test(value) || /\s#/.test(value)) return true;
  if (/^(true|false|null|yes|no|on|off|~)$/i.test(value)) return true;
  if (/^-?\d+(\.\d+)?$/.test(value)) return true;
  if (/[\n\r\t]/.test(value)) return true;
  return false;
}
