/**
 * Properties every backend must satisfy.
 *
 * A backend is free to choose its own idiom, but not free to lose information:
 * whatever the source declared has to appear in the output, and whatever it did
 * not declare must not.
 */
import { describe, expect, it } from 'vitest';
import { codeGenerators, generateProject } from '../src/index.js';
import { ordersProject } from './helpers.js';

const project = ordersProject();

const outputs = codeGenerators.all().map((generator) => ({
  generator,
  result: generateProject(generator, { project, outputDir: `out/${generator.id}`, options: {} }),
}));

describe.each(outputs)('the $generator.id backend', ({ generator, result }) => {
  const all = result.files.map((f) => f.contents).join('\n');

  it('emits files', () => {
    expect(result.files.length).toBeGreaterThan(5);
    expect(result.diagnostics.filter((d) => d.severity === 'error')).toEqual([]);
  });

  it('gives every file a distinct relative path with forward slashes', () => {
    const paths = result.files.map((f) => f.path);
    expect(new Set(paths).size).toBe(paths.length);
    for (const path of paths) {
      expect(path).not.toMatch(/\\/);
      expect(path.startsWith('/')).toBe(false);
      expect(path).not.toContain('..');
    }
  });

  it('marks every generated file as generated', () => {
    for (const generated of result.files) {
      if (!/\.(ts|java|py|go|rs)$/.test(generated.path)) continue;
      expect(generated.contents).toContain('Generated by AI-Lang');
    }
  });

  it('emits no empty files', () => {
    for (const generated of result.files) expect(generated.contents.trim().length).toBeGreaterThan(0);
  });

  it('carries every declared name into the output', () => {
    for (const name of ['Order', 'OrderItem', 'Money', 'OrderStatus', 'OrderPlaced', 'PlaceOrder', 'OrderNotFound']) {
      expect(all).toContain(name);
    }
  });

  it('carries the invariant text so a failure names the rule it broke', () => {
    expect(all).toContain('an order must hold at least one item');
  });

  it('carries the declared HTTP status of every checked error', () => {
    expect(all).toMatch(/\b404\b/);
    expect(all).toMatch(/\b409\b/);
    expect(all).toMatch(/\b422\b/);
  });

  it('carries both declared routes', () => {
    expect(all).toContain('/orders/');
    expect(all).toContain('/products/');
  });

  it('depends on ports, never on adapters', () => {
    const applicationLayer = result.files.filter((f) => /application|service/i.test(f.path));
    for (const generated of applicationLayer) {
      expect(generated.contents).not.toContain('SqlOrderRepository');
      expect(generated.contents).not.toContain('EmailCustomerNotifier');
    }
  });

  it('invents nothing the source did not declare', () => {
    // The catalogue declares no events, commands or handlers.
    for (const invented of ['ProductCreated', 'ProductRepositoryFactory', 'AbstractOrderService']) {
      expect(all).not.toContain(invented);
    }
  });

  it('states a toolchain command that can verify its output', () => {
    expect(generator.verifyCommand?.length ?? 0).toBeGreaterThan(0);
  });

  it('never writes a secret value into the output', () => {
    // A secret may appear as a name, as an empty slot, or as a `${...}` reference.
    // Anything else means the compiler invented a value.
    const literal = /DB_PASSWORD[ \t]*[=:][ \t]*["']?([^\s"'${}][^\s"'}]*)/g;
    expect([...all.matchAll(literal)].map((m) => m[1])).toEqual([]);
  });
});

describe('the registry', () => {
  it('exposes every target the language documents', () => {
    expect(codeGenerators.ids()).toEqual(['go', 'java', 'python', 'rust', 'typescript']);
  });

  it('refuses a duplicate registration', () => {
    expect(() => codeGenerators.register(codeGenerators.require('typescript'))).toThrow(/duplicate/);
  });
});

describe('ordered comparisons', () => {
  it('never uses a relational operator on a type that lacks one', () => {
    // Instant and time.Time are ordered but have no `<`; the backends route
    // through a helper instead. Regression for a real Java compile failure.
    const java = outputs.find((o) => o.generator.id === 'java')!.result;
    const go = outputs.find((o) => o.generator.id === 'go')!.result;

    const javaSource = java.files.map((f) => f.contents).join('\n');
    expect(javaSource).toContain('public final class Ordering');
    expect(javaSource).toContain('Ordering.gt(');

    const goSource = go.files.map((f) => f.contents).join('\n');
    expect(goSource).toContain('func compareOrdered(');
    expect(goSource).toContain('shared.Gt(');
  });
});
