export { analyze, defaultPasses, type AnalyzeOptions, type AnalysisResult } from './analyze.js';
export { type AnalysisContext, type SemanticPass, Scope, suggest, withSuggestion } from './context.js';
export { TypeChecker } from './type-checker.js';
export { symbolPass } from './passes/symbols.js';
export { typePass } from './passes/types.js';
export { dddPass } from './passes/ddd.js';
export { errorFlowPass } from './passes/error-flow.js';
export { architecturePass } from './passes/architecture.js';
export { simplicityPass } from './passes/simplicity.js';
export { nativePass } from './passes/native.js';
export { walkStatements, walkExpressions, walkExpression, typesReferencedBy, typesOfDeclaration, bodies } from './walk.js';
export { Interpreter, DomainFailure, Unsupported, DeferredToTarget } from './interpreter/runtime.js';
export { runScenarios, type ScenarioResult, type TestReport, type Outcome } from './interpreter/scenarios.js';
export { Trace, renderTrace, brief, type TraceStep, type TraceKind } from './interpreter/trace.js';
export { show, equals, isRecord, record, type Value, type RecordValue } from './interpreter/values.js';
